name = "repost-club"
main = "src/index.js"
compatibility_date = "2026-09-10"

[vars]
INSTAGRAM_APP_ID = "1632280991870398"
INSTAGRAM_REDIRECT_URI = "https://repost-club.alandiaz145.workers.dev/api/instagram/callback"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "repost-club-db"
database_id = "e0056d93-cc02-4151-83df-51b0929b61c3"
